stages:
  - build
  - deploy

publish:
  image: curlimages/curl:latest
  stage: build
  variables:
    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
  script:
    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
    - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
    - code=$(echo "$response" | tail -n 1)
    - body=$(echo "$response" | head -n 1)
    # Output state information
    - if [ $code -eq 201 ]; then
        echo "Package created - Code $code - $body";
      else
        echo "Could not create package - Code $code - $body";
        exit 1;
      fi
  tags:
    - gitlab
 
production:
  stage: deploy
  script:
     
    # host= host
    # mode= prod, test, dev
    # module_name=
    # project_dir= target directory
    # folder= temporary directory
    # modules= moudules that composer will install (все модули в одну строку, через пробел, как в композере)
    # php= php version 8.0, 7.4
    # composer= composer version 2
    - ansible-playbook ./deploy.yml
      -e host="$COLIBRI_PROD_DOMAIN"
      -e mode="prod"
      -e ui_version="master" 
      -e module_name="auth"
      -e project_dir="auth.com"
      -e folder="ecolo-place_dist"
      -e "modules=['colibri/security:dev-master','colibri/mainframe:dev-master','colibri/manage:dev-master','colibri/sites:dev-master','colibri/tools:dev-master','colibri/lang:dev-master','evabeta/auth:$CI_COMMIT_REF_NAME']"
      -e "bin_scripts=['auth-migrate.sh']"
      -e php=8.0
      -e composer=2
 
  when: manual
  only:
    - tags
  tags:
    - gitlab
 
test:
  stage: deploy
  script:
 
    # host= host
    # mode= prod, test, dev
    # module_name=
    # project_dir= target directory
    # folder= temporary directory
    # modules= moudules that composer will install (все модули в одну строку, через пробел, как в композере)
    # php= php version 8.0, 7.4
    # composer= composer version 2
    - ansible-playbook ./deploy.yml
      -e host="$COLIBRI_TEST_DOMAIN"
      -e mode="test"
      -e ui_version="master" 
      -e module_name="auth"
      -e project_dir="auth.com"
      -e folder="ecolo-place_dist"
      -e "modules=['colibri/security:dev-master','colibri/mainframe:dev-master','colibri/manage:dev-master','colibri/sites:dev-master','colibri/tools:dev-master','colibri/lang:dev-master','evabeta/auth:dev-$CI_COMMIT_REF_NAME']"
      -e "bin_scripts=['auth-migrate.sh']"
      -e php=8.0
      -e composer=2
  when: always
  only:
    - dev
  tags:
    - gitlab